### ISSUE TITLE
error: undefined reference to 'jpeg_destroy_compress'

### ISSUE THREAD

**Issue by haojinku** [JerryChan123/Libjpeg#1]
Libjpeg-master/app/src/main/cpp/native-lib.cpp:82: error: undefined reference to 'jpeg_destroy_compress'
demo 下载后编译直接报这个错，要怎么修改

**Comment by gitgeek4dx** [comment]
同遇到了，用extern 'C' 把导入头文件包裹起来也不行

**Comment by gitgeek4dx** [comment]
> 同遇到了，用 extern 'C' 把导入头文件包裹起来也不行

是CmakeLists.txt的问题，作者把abi写死为arm64了，改为 ${ANDROID_ABI}即可：
set_target_properties(libjpeg
        PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/${ANDROID_ABI}/libjpeg.so)
